version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: plate-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
#    depends_on:
#     - your-application
    networks:
      - plate-network

networks:
  plate-net:
    driver: bridge
